In [ ]:
import pandas as pd
import numpy as np

## Read in Our Data

In [ ]:
aaplNewsStock = pd.read_csv('/content/sample_data/AppleNewsStock.csv')
msftNewsStock = pd.read_csv('/content/sample_data/MicrosoftNewsStock.csv')
redditNews    = pd.read_csv('/content/sample_data/RedditNews.csv')
djia          = pd.read_csv('/content/sample_data/upload_DJIA_table.csv')

## Combine `redditNews` and `djia` so that we can get a news column for every date that contains a string of all the news on a given day

In [1]:
uniqueDates = redditNews.groupby('Date')
newsDic = {}
for date,group in uniqueDates:
  for news in (group['News'].to_list()):
    if date in newsDic:
      newsDic[date][0] += news
    else:
      newsDic[date] = [news]
redditNewsByDate = pd.DataFrame.from_dict(newsDic,'index')
redditNewsByDate.columns = ['News']
redditNewsByDate['Date'] = redditNewsByDate.index
redditNewsByDate = redditNewsByDate.reindex(columns = ['Date', 'News'])
redditNewsByDate = redditNewsByDate.reset_index(drop=True)

NameError: ignored

In [ ]:
djiaNewsStock = pd.merge(djia, redditNewsByDate, how ='inner', on ='Date')

## View and Add Labels to the NewsStock Dataframes

In [ ]:
aaplNewsStock = aaplNewsStock.reindex(columns = ['Date', 'Open', 'Adj Close', 'Close', 'High', 'Low', 'Volume', 'News']).dropna(axis = 0).reset_index(drop=True).sort_values(by='Date')
print(aaplNewsStock.shape)
labelLst = []
nrows = aaplNewsStock.shape[0]
for i in range(nrows):
  if aaplNewsStock.iloc[i,1] > aaplNewsStock.iloc[i,2]:
    labelLst.append(0)
  else:
    labelLst.append(1)
aaplNewsStock['Label'] = labelLst
aaplNewsStock.head()

(2323, 8)

         Date  ...  Label
0  2006-12-01  ...      0
1  2006-12-04  ...      0
2  2006-12-06  ...      0
3  2006-12-07  ...      0
4  2006-12-08  ...      1

[5 rows x 9 columns]

In [ ]:
msftNewsStock = msftNewsStock.drop(columns=['Unnamed: 0']).dropna(axis = 0).reset_index(drop=True).sort_values(by='Date')
msftNewsStock = msftNewsStock.reindex(columns = ['Date', 'Open', 'Adj Close', 'Close', 'High', 'Low', 'Volume', 'News'])
print(msftNewsStock.shape)
labelLst = []
nrows = msftNewsStock.shape[0]
for i in range(nrows):
  if msftNewsStock.iloc[i,1] > msftNewsStock.iloc[i,2]:
    labelLst.append(0)
  else:
    labelLst.append(1)
msftNewsStock['Label'] = labelLst
msftNewsStock.head()

(1341, 8)

         Date  ...  Label
0  2006-12-04  ...      1
1  2006-12-06  ...      0
2  2006-12-07  ...      0
3  2006-12-12  ...      0
4  2006-12-13  ...      0

[5 rows x 9 columns]

In [ ]:
djiaNewsStock = djiaNewsStock.reindex(columns = ['Date', 'Open', 'Adj Close', 'Close', 'High', 'Low', 'Volume', 'News']).dropna(axis = 0).sort_values(by='Date').reset_index(drop=True)
print(djiaNewsStock.shape)
labelLst = []
nrows = djiaNewsStock.shape[0]
for i in range(nrows):
  if djiaNewsStock.iloc[i,1] > djiaNewsStock.iloc[i,2]:
    labelLst.append(0)
  else:
    labelLst.append(1)
djiaNewsStock['Label'] = labelLst
djiaNewsStock.head()

(1989, 8)

         Date  ...  Label
0  2008-08-08  ...      1
1  2008-08-11  ...      1
2  2008-08-12  ...      0
3  2008-08-13  ...      0
4  2008-08-14  ...      1

[5 rows x 9 columns]

## Add Polarity Scores for Each News Using NLTK

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.6/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from nltk) (1.15.0)

In [ ]:
import nltk
nltk.download('vader_lexicon') # one time only (Valence Aware Dictionary and sEntiment Reasoner)
from nltk.sentiment.vader import SentimentIntensityAnalyzer
vader = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

/usr/local/lib/python3.6/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

In [ ]:
negLst = []
neuLst = []
posLst = []
comLst = []

nrows = djiaNewsStock.shape[0]
for i in range(nrows):
  s = str(djiaNewsStock.iloc[i,7])
  pScores = vader.polarity_scores(s)
  neg = pScores['neg']
  negLst.append(neg)
  neu = pScores['neu']
  neuLst.append(neu)
  pos = pScores['pos']
  posLst.append(pos)
  com = pScores['compound']
  comLst.append(com)

djiaNewsStock['neg'] = negLst
djiaNewsStock['neu'] = neuLst
djiaNewsStock['pos'] = posLst
djiaNewsStock['compound'] = comLst

djiaNewsStock = djiaNewsStock.reindex(columns = ['Date', 'Open', 'Adj Close', 'Close', 'High', 'Low', 'Volume', 'News', 'neg', 'neu', 'pos', 'compound', 'Label'])
djiaNewsStock

            Date          Open     Adj Close  ...    pos  compound  Label
0     2008-08-08  11432.089844  11734.320312  ...  0.062   -0.9966      1
1     2008-08-11  11729.669922  11782.349609  ...  0.092   -0.9075      1
2     2008-08-12  11781.700195  11642.469727  ...  0.056   -0.9739      0
3     2008-08-13  11632.809570  11532.959961  ...  0.048   -0.9842      0
4     2008-08-14  11532.070312  11615.929688  ...  0.093   -0.9774      1
...          ...           ...           ...  ...    ...       ...    ...
1984  2016-06-27  17355.210938  17140.240234  ...  0.090   -0.9683      0
1985  2016-06-28  17190.509766  17409.720703  ...  0.100   -0.9633      1
1986  2016-06-29  17456.019531  17694.679688  ...  0.076   -0.9968      1
1987  2016-06-30  17712.759766  17929.990234  ...  0.053   -0.9978      1
1988  2016-07-01  17924.240234  17949.369141  ...  0.060   -0.9980      1

[1989 rows x 13 columns]

In [ ]:
negLst = []
neuLst = []
posLst = []
comLst = []

nrows = msftNewsStock.shape[0]
for i in range(nrows):
  s = str(msftNewsStock.iloc[i,7])
  pScores = vader.polarity_scores(s)
  neg = pScores['neg']
  negLst.append(neg)
  neu = pScores['neu']
  neuLst.append(neu)
  pos = pScores['pos']
  posLst.append(pos)
  com = pScores['compound']
  comLst.append(com)

msftNewsStock['neg'] = negLst
msftNewsStock['neu'] = neuLst
msftNewsStock['pos'] = posLst
msftNewsStock['compound'] = comLst

msftNewsStock = msftNewsStock.reindex(columns = ['Date', 'Open', 'Adj Close', 'Close', 'High', 'Low', 'Volume', 'News', 'neg', 'neu', 'pos', 'compound', 'Label'])
msftNewsStock

            Date       Open  Adj Close  ...    pos  compound  Label
0     2006-12-04  29.230000  29.330000  ...  0.000   -0.7783      1
1     2006-12-06  29.100000  28.990000  ...  0.102    0.9003      0
2     2006-12-07  28.959999  28.850000  ...  0.190    0.6597      0
3     2006-12-12  29.559999  29.430000  ...  0.000    0.0000      0
4     2006-12-13  29.600000  29.549999  ...  0.167    0.5574      0
...          ...        ...        ...  ...    ...       ...    ...
1336  2016-11-14  59.020000  58.119999  ...  0.181    0.7351      0
1337  2016-11-15  58.330002  58.869999  ...  0.186    0.1280      1
1338  2016-11-18  60.779999  60.349998  ...  0.000   -0.4215      0
1339  2016-11-22  60.980000  61.119999  ...  0.000    0.0000      1
1340  2016-11-23  61.009998  60.400002  ...  0.158    0.8478      0

[1341 rows x 13 columns]

In [ ]:
negLst = []
neuLst = []
posLst = []
comLst = []

nrows = aaplNewsStock.shape[0]
for i in range(nrows):
  s = str(aaplNewsStock.iloc[i,7])
  pScores = vader.polarity_scores(s)
  neg = pScores['neg']
  negLst.append(neg)
  neu = pScores['neu']
  neuLst.append(neu)
  pos = pScores['pos']
  posLst.append(pos)
  com = pScores['compound']
  comLst.append(com)

aaplNewsStock['neg'] = negLst
aaplNewsStock['neu'] = neuLst
aaplNewsStock['pos'] = posLst
aaplNewsStock['compound'] = comLst

aaplNewsStock = aaplNewsStock.reindex(columns = ['Date', 'Open', 'Adj Close', 'Close', 'High', 'Low', 'Volume', 'News', 'neg', 'neu', 'pos', 'compound', 'Label'])
aaplNewsStock

            Date        Open   Adj Close  ...    pos  compound  Label
0     2006-12-01   13.114285   13.045714  ...  0.063    0.7707      0
1     2006-12-04   13.125714   13.017143  ...  0.085    0.8720      0
2     2006-12-06   12.948571   12.832857  ...  0.093    0.6858      0
3     2006-12-07   12.861428   12.434286  ...  0.040   -0.6712      0
4     2006-12-08   12.461429   12.608571  ...  0.069   -0.1796      1
...          ...         ...         ...  ...    ...       ...    ...
2318  2016-11-17  109.809998  109.949997  ...  0.086    0.9231      1
2319  2016-11-18  109.720001  110.059998  ...  0.101    0.7932      1
2320  2016-11-21  110.120003  111.730003  ...  0.097   -0.6908      1
2321  2016-11-22  111.949997  111.800003  ...  0.084   -0.8885      0
2322  2016-11-25  111.129997  111.790001  ...  0.000   -0.8990      1

[2323 rows x 13 columns]

## Save as `.CSV`

In [ ]:
aaplNewsStock.to_csv('aaplNewsStock.csv') 
msftNewsStock.to_csv('msftNewsStock.csv')
djiaNewsStock.to_csv('djiaNewsStock.csv')